### ISSUE TITLE
install not working

### ISSUE THREAD

**Issue by sboen2022** [MaestSi/ONToHap#2]
Hi, 
I tried installing ONToHap as described on the site but I get the following message, then it just stays on solving environment but doesn't move forward with the installation.

Collecting package metadata (current_repodata.json): done
Solving environment: failed with repodata from current_repodata.json, will retry with next repodata source.
Collecting package metadata (repodata.json): done
Solving environment: /

Could you please advise how to resolve this?
cheers

**Comment by sboen2022** [comment]
sorry guys, patience was key :)

**Comment by MaestSi** [comment]
Patience is the virtue of the strong! :)
Best,
simone
