### ISSUE TITLE
vcf output file not phased

### ISSUE THREAD

**Issue by sboen2022** [MaestSi/ONToHap#3]
Hi guys,
sorry to bother you. 
I tried running ONToHap but unfortunately the resulting .vcf file is not phased (showing 0/1 or 1/1 instead of 0|1 or 1|1).
I have attached the nohup.out file.  Is there something I can do to resolve this?
thanks a lot for your help.
best wishes
[nohup -.pdf](https://github.com/MaestSi/ONToHap/files/8512602/nohup.-.pdf)

**Comment by MaestSi** [comment]
Hi,
based on the nohup file it looks like you are working with a multi-reference fasta, is this the case? If yes, vcf files merging may not work as expected, as it is intended to deal with amplicon data, which usually result in one single haplo-block. Do also vcf files produced using each reads subset (e.g. ..../100_reads_subsets_Minimap2_HapCUT2/100_reads_subset_<X>/hapcut2_output.phased.VCF) contain only unphased variants?
Simone

**Comment by sboen2022** [comment]
Hi Simone,
thanks a lot for your very quick reply! 
Yes, that is correct, we are using a multi-reference fasta for 3 genes. I have tried separating the reference fasta, but unfortunately the resulting .vcf was not phased either. I can still try separating the reads themselves.

Yes, the 100 reads subsets also contain only unphased variants.

Is there anything else I can try?
all the best

**Comment by MaestSi** [comment]
I also noticed a seqtk "permission denied" error. Can you please check that fastq and bam files are not empty?
Simone

**Comment by sboen2022** [comment]
you are right, the 100 read fastq files are indeed empty. so are the hapcut2 output files.
the original fastq files which contain the reads are fine. 

we followed this input structure:
sh Launch_ONToHap.sh -f <fastq_reads> -u <unphased_vcf> -r <reference_fasta> -o <output_dir>
are we missing an argument to enter a bam file?

all the best

**Comment by MaestSi** [comment]
No, the bam file should be produced by aligning fastq reads to the reference file by the pipeline. Just check that
```
source activate ONToHap_env
seqtk
```
produces the help message for seqtk. Otherwise, you should try reinstalling it, or specifying a different path inside tools.sh script.
Best,
Simone

**Comment by sboen2022** [comment]
Hi Simone
this part works. all the commands for seqtk are listed.
best wishes

**Comment by MaestSi** [comment]
So, if you want to be sure that a specific seqtk version is executed, you may open tools.sh and substitute the SEQTK line with the output of `which seqtk`, with something like:
`SEQTK=<output of which seqtk>`
Let me know if the pipeline runs after this!
Best,
Simone

**Comment by sboen2022** [comment]
good morning Simone
I tried changing the SEQTK line as you suggested. I also tried reinstalling seqtk to a different location and using that path. 
unfortunately, I still get the same error message in the nohup file with exactly the same path as before. 
Changing the seqtk path in the config file also had no effect.
best wishes

**Comment by sboen2022** [comment]
Hi Simone,
so, I completely reinstalled miniconda and ONToHap and this seems to have solved the seqtk problem. 
I now get at least a partially phased .vcf file. 
I will try running the program for each gene separately to see if this improves results. 
best wishes

**Comment by MaestSi** [comment]
Hi, sorry for not answering back. Could you please check in IGV one of your bam files and see if you have any reads spanning 2 heterozygous SNVs which have not been phased by HapCUT2?
Best,
Simone

**Comment by sboen2022** [comment]
Hi, sorry for the delay - 
2 of the three genes are almost completely phased (except at the very end of the amplicon - but this is ok). However, the third gene is not phased at all, despite several heterozygous SNVs. I checked different samples and it's the same in all of them.  
All the best

**Comment by MaestSi** [comment]
That's quite strange if you have reads that span multiple SNVs. Maybe you could try out another phaser, such as WhatsHap or Hapchat. Let me know if you try them out!
Best,
Simone

**Comment by sboen2022** [comment]
I already tried whatshap - with that tool all 3 genes are completely phased (again with the exception of the very end of the amplicons).
best wishes

**Comment by MaestSi** [comment]
Ok. I will close the issue. Feel free to open another one in case you have any additional doubts/issues with the pipeline!
Best,
Simone
